'use client';

import IntroNavbar from '@/components/intro/IntroNavbar';
import NeuralSingularity from '@/components/landing/NeuralSingularity';
import { motion } from 'framer-motion';
import { Quote } from 'lucide-react';

export default function FoundersPage() {
  return (
    <main className="min-h-screen bg-black text-white selection:bg-[#D4AF37]">
      <IntroNavbar />
      
      {/* 1. HERO SECTION */}
      <section className="pt-40 pb-20 px-6 max-w-4xl mx-auto text-center">
        
        {/* CIRCULAR ELON FRAME */}
        <motion.div 
          initial={{ scale: 0 }} 
          animate={{ scale: 1 }} 
          transition={{ type: "spring", stiffness: 100 }}
          className="relative w-64 h-64 mx-auto mb-12"
        >
           {/* Animated Border Ring */}
           <div className="absolute inset-0 rounded-full border-2 border-dashed border-[#D4AF37] animate-spin-slow" style={{ animationDuration: '20s' }} />
           <div className="absolute -inset-4 rounded-full border border-white/10" />
           
           {/* The Image - FIXED: ALWAYS COLORED */}
           <div className="w-full h-full rounded-full overflow-hidden border-4 border-[#111] shadow-[0_0_50px_rgba(212,175,55,0.3)] bg-gray-800">
              <img 
                src="https://upload.wikimedia.org/wikipedia/commons/e/ed/Elon_Musk_Royal_Society.jpg" 
                alt="Elon Musk" 
                className="w-full h-full object-cover" 
              />
           </div>

           {/* Badge */}
           <div className="absolute bottom-0 right-4 bg-[#D4AF37] text-black text-xs font-bold px-4 py-1 rounded-full uppercase tracking-widest">
              Technoking
           </div>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
          <h1 className="text-5xl md:text-8xl font-serif mb-8 text-white">The Architect.</h1>
          <p className="text-[#D4AF37] font-mono text-sm uppercase tracking-[0.3em] mb-12">
             Elon Reeve Musk • Founder & Visionary
          </p>
        </motion.div>

        {/* 2. THE WRITE UP (MARS MANIFESTO) */}
        <div className="text-left bg-[#111] p-10 md:p-16 rounded-[3rem] border border-white/10 relative overflow-hidden">
           <Quote className="absolute top-10 left-10 text-[#D4AF37]/20" size={100} />
           
           <div className="relative z-10 space-y-8 text-lg text-gray-300 font-light leading-relaxed">
              <p>
                 <span className="text-white font-bold text-2xl">Civilization is fragile.</span> The window of opportunity to become a multi-planetary species 
                 will not remain open forever. To secure the light of consciousness, we must build a self-sustaining city on Mars.
              </p>
              <p>
                 But space exploration is capital intensive. Traditional financing models—Wall Street banks, venture capital, 
                 government grants—are too slow, too risk-averse, and too short-sighted. 
                 <span className="text-[#D4AF37]"> We needed a perpetual motion machine for capital generation.</span>
              </p>
              <p>
                 That is why <strong>TeslaInvest</strong> was built. By redirecting the idle processing power of the 
                 Dojo Supercomputer during off-peak hours, we unlocked the ability to predict market volatility with 
                 99.9% accuracy.
              </p>
              <p>
                 Every dollar of profit generated by this platform serves two purposes: 
                 <br/>1. Expanding your personal wealth.
                 <br/>2. Funding the Starship program to take humanity to the stars.
              </p>
           </div>
        </div>

      </section>

      {/* 3. CRAZY ANIMATION SECTION */}
      <section className="py-20 px-6 max-w-6xl mx-auto text-center">
         <h2 className="text-3xl font-serif mb-8">The Engine: Neural Singularity</h2>
         <NeuralSingularity />
      </section>

    </main>
  );
}
